### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Aftermath#1]
@RamonGilabert told me one day that the current name of the library is not that good. It means we need a new one, asap @zenangst @onmyway133

**Comment by RamonGilabert** [comment]
That's bs.

**Comment by sindrenm** [comment]
:laughing:

**Comment by zenangst** [comment]
- Aftermath
- Fallout
- Waves
- Imperium
- Motus
- Epicinium
- Swiftness
- Rapid
- Effect
- Do
- Discharge

**Comment by RamonGilabert** [comment]
Aftermath.

**Comment by zenangst** [comment]
Added a few more to the list.

**Comment by vadymmarkov** [comment]
Kinda like Aftermath.

**Comment by vadymmarkov** [comment]
Closed by https://github.com/hyperoslo/Aftermath/pull/2

**Comment by zenangst** [comment]
Yay
