### ISSUE TITLE
Aftermath and CQRS

### ISSUE THREAD

**Issue by vadymmarkov** [hyperoslo/Aftermath#4]
@zenangst @RamonGilabert @onmyway133 

Some ideas were taken from CQRS https://en.wikipedia.org/wiki/Command–query_separation principle, but in general there is at least one fundamental difference - we don't separate a query layer that only returns data to the caller and a command layer that only updates the state. Aftermath is for front-end apps where both read and update actions go through the same flow:

Command ->  Handler -> Event -> Reaction

With that being said, should we care about terms that could potentially lead people into confusion? For example, Command could be renamed to Intent or even Action.

**Comment by onmyway133** [comment]
@vadymmarkov What does `Command` do in this flow?

**Comment by vadymmarkov** [comment]
@onmyway133 `Command` is any kind of request from the view, could be "Load posts" or "Update post". It's handled by `CommandHandler` where all the business logic is, such as networking or database queries. When `CommandHandler` is done, it produces some response, either success or error, and publishes it to single/multiple event subscribers.

**Comment by zenangst** [comment]
We could go with Action to avoid confusion.

**Comment by zenangst** [comment]
Ops, I totally closed by mistake, stupid jumpy subway ride.

**Comment by vadymmarkov** [comment]
I was thinking about it and for me "Load post!" or "Update post!" are more commands than actions. So let's not make a problem from it, leave Command as a name and see how it goes.

**Comment by zenangst** [comment]
I do agree with you here, but if you think about the flow that you referred to before;

```
Command -> Handler -> Event -> Reaction
```

The end result of an action is a reaction right? 😁
